apiVersion: v2
name: auditor-kubernetes-stack
description: AUDITOR collctor stack for Kubernetes
type: application
version: 0.8.3
appVersion: 0.8.3
kubeVersion: '>=1.28.0-0'
home: https://alu-schumacher.github.io/AUDITOR
dependencies:
- name: auditor
  repository: https://rkleinem.github.io/helmcharts/
  condition: auditor.enabled
- name: auditor-collector
  repository: https://rkleinem.github.io/helmcharts/
  condition: auditor-collctor.enabled
- name: auditor-prometheus
  repository: https://rkleinem.github.io/helmcharts/
  condition: auditor-prometheus.enabled
- name: auditor-apel
  repository: https://rkleinem.github.io/helmcharts/
  condition: auditor-apel.enabled

