apiVersion: v2
name: auditor-kubernetes-stack
description: AUDITOR collctor stack for Kubernetes
type: application
version: 0.10.2-1
appVersion: 0.10.2
kubeVersion: '>=1.28.0-0'
home: https://alu-schumacher.github.io/AUDITOR
icon: https://github.com/ALU-Schumacher/AUDITOR/blob/a409f6a9f2ce7f5b1c15b447d53d62ab6389826b/media/website/content/auditorlogo_transparent.png

