apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "auditor-prometheus.clusterRoleName" . }}
  labels:
    {{- include "auditor-prometheus.labels" . | nindent 4 }}
  annotations:
    {{- merge .Values.clusterRole.annotations .Values.commonAnnotations | toYaml | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - nodes/stats
  #- nodes/proxy
  #- nodes/spec
  #- nodes/log
  verbs:
  - 'get'
  - 'list'
  - 'watch'
