apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auditor-prometheus.serviceAccountName" . }}
  labels:
    {{- include "auditor-prometheus.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge .Values.secret.annotations .Values.commonAnnotations }}
    {{- $_ := set $annotations "kubernetes.io/service-account.name" (include "auditor-prometheus.serviceAccountName" .) }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/service-account-token
