apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auditor-prometheus.serviceAccountName" . }}
  labels:
    {{- include "auditor-prometheus.labels" . | nindent 4 }}
  annotations: 
    {{- merge .Values.serviceAccount.annotations .Values.commonAnnotations | toYaml | nindent 4 }}
#automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
