apiVersion: v1
kind: Secret
metadata:
  name: auditor-secrets-postgres
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (deepCopy .Values.auditor.commonAnnotations) .Values.auditor.secret.annotations }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  password: {{ b64enc .Values.auditor.config.database.password }}
---
{{ if .Values.auditor.config.tls_config.use_tls }}
apiVersion: v1
kind: Secret
metadata:
  name: auditor-secrets-auditor
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (deepCopy .Values.global.commonAnnotations) .Values.auditor.secret.annotations }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.auditor.certs.auditor_cert | b64enc }}
    {{- else }}
    {{ .Values.auditor.certs.auditor_cert | b64enc }}
    {{- end }}
  tls.key: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.auditor.certs.auditor_key | b64enc }}
    {{- else }}
    {{ .Values.auditor.certs.auditor_key | b64enc }}
    {{- end }}
{{ end }}
