apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
  annotations: 
    {{- (include "collector.commonAnnotations" .) | nindent 4 }}
