{{ if .Values.collector.config.tls_config.use_tls }}
apiVersion: v1
kind: Secret
metadata:
  name: collector-secrets
  labels:
    {{- include "collector.labels" . | nindent 4 }}
  annotations:
    {{- (include "collector.commonAnnotations" .) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.collector.certs.collector_cert | b64enc }}
    {{- else }}
    {{ .Values.collector.certs.collector_cert | b64enc }}
    {{- end }}
  tls.key: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.collector.certs.collector_key | b64enc }}
    {{- else }}
    {{ .Values.collector.certs.collector_key | b64enc }}
    {{- end }}
{{ end }}

