apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (deepCopy .Values.global.commonAnnotations) .Values.prometheus.commonAnnotations }}
    {{- $_ := set $annotations "kubernetes.io/service-account.name" (include "prometheus.fullname" .) }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/service-account-token
---
{{ if .Values.prometheus.config.use_tls }}
apiVersion: v1
kind: Secret
metadata:
  name: prom-certs
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (deepCopy .Values.global.commonAnnotations) .Values.prometheus.commonAnnotations }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.prometheus.certs.prom_cert | b64enc }}
    {{- else }}
    {{ .Values.prometheus.certs.prom_cert | b64enc }}
    {{- end }}
  tls.key: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.prometheus.certs.prom_key | b64enc }}
    {{- else }}
    {{ .Values.prometheus.certs.prom_key | b64enc }}
    {{- end }}
{{ end }}
