{{ if .Values.apelReporter.enabled }}
{{ if .Values.apelReporter.config.auditor.use_tls }}
apiVersion: v1
kind: Secret
metadata:
  name: reporter-auditor-certs
  labels:
    {{- include "auditor-apel.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (include "auditor-apel.commonAnnotations" . | fromYaml) .Values.apelReporter.secret.annotations }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.apelReporter.auditorcerts.reporter_cert | b64enc }}
    {{- else }}
    {{ .Values.apelReporter.auditorcerts.reporter_cert | b64enc }}
    {{- end }}
  tls.key: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.apelReporter.auditorcerts.reporter_key | b64enc }}
    {{- else }}
    {{ .Values.apelReporter.auditorcerts.reporter_key | b64enc }}
    {{- end }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: reporter-apel-certs
  labels:
    {{- include "auditor-apel.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (include "auditor-apel.commonAnnotations" . | fromYaml) .Values.apelReporter.secret.annotations }}
    {{- toYaml $annotations | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.apelReporter.apelcerts.apelclient_cert | b64enc }}
    {{- else }}
    {{ .Values.apelReporter.apelcerts.apelclient_cert | b64enc }}
    {{- end }}
  tls.key: |
    {{- if .Values.global.certs.useFiles }}
    {{ .Files.Get .Values.apelReporter.apelcerts.apelclient_key | b64enc }}
    {{- else }}
    {{ .Values.apelReporter.apelcerts.apelclient_key | b64enc }}
    {{- end }}
{{ end }}
