apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "auditor-collector.clusterRoleName" . }}
  labels:
    {{- include "auditor-collector.labels" . | nindent 4 }}
  annotations: 
    {{- $annotations := merge .Values.commonAnnotations .Values.clusterRole.annotations }}
    {{- toYaml $annotations | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "auditor-collector.clusterRoleName" . }}
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: ServiceAccount
  name: {{ include "auditor-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
