apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auditor-collector.serviceAccountName" . }}
  labels:
    {{- include "auditor-collector.labels" . | nindent 4 }}
  annotations: 
    {{- $annotations := merge .Values.commonAnnotations .Values.serviceAccount.annotations }}
    {{- toYaml $annotations | nindent 4 }}
#automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
