apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auditor.fullname" . }}
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge .Values.commonAnnotations .Values.config.annotations }}
    {{- toYaml $annotations | nindent 4 }}
data:
  auditor.yml: |-
    application:
      addr:
        {{- toYaml .Values.config.application.addr | nindent 8 }}
      port: {{ include "auditor.serverport" . }}
    database:
      {{- toYaml .Values.config.database | nindent 6 }}
    metrics:
      {{- toYaml .Values.config.metrics | nindent 6 }}
    log_level: {{ default "info" .Values.config.logLevel }}
