apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge .Values.commonAnnotations .Values.secret.annotations }}
    {{- toYaml $annotations | nindent 4 }}
type: Opaque
data:
  password: {{ b64enc .Values.config.database.password }}
