apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "auditor.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge .Values.commonAnnotations .Values.service.annotations }}
    {{- toYaml $annotations | nindent 4 }}
spec:
  type: {{ quote .Values.service.type }}
  selector:
    app: {{ include "auditor.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ include "auditor.serverport" . }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
